version: "3.9"

services:
  event_store:
    command:
      - "postgres"
      - "-c"
      - "max_connections=500"


    image: library/postgres:10.12
    environment:
      - POSTGRES_DB=event_store
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "35231:5432"

  postgres_projections:
    command:
      - "postgres"
      - "-c"
      - "max_connections=500"

    image: library/postgres:10.12
    environment:
      - POSTGRES_DB=projections
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "35232:5432"