version: "3.9"

services:
  pg_journal_command:
    command:
      - "postgres"
    image: library/postgres:10.12
    environment:
      - POSTGRES_DB=pg_journal_command
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "30000:5432"

  pg_journal_query:
    command:
      - "postgres"
    image: library/postgres:10.12
    environment:
      - POSTGRES_DB=pg_journal_query
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "30001:5432"