version: "3.9"

services:
  event_store:
    command:
      - "postgres"
    image: library/postgres:10.12
    environment:
      - POSTGRES_DB=event_store
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "30000:5432"