version: "3.9"

services:
  postgres:
    command:
      - "postgres"
    image: postgres
    environment:
      - POSTGRES_DB=mmorpg-backpack
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "6338:5432"