version: "3.9"

services:
  postgres_event_store:
    command:
      - "postgres"
      - "-c"
      - "max_connections=500"


    image: library/postgres:10.12
    environment:
      - POSTGRES_DB=benchmarks
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "36000:5432"


  eventstoredb_event_store:
    image: eventstore/eventstore:21.2.0-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=none
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true

    ports:
      - "1113:1113"
      - "36001:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

volumes:
  eventstore-volume-data:
  eventstore-volume-logs: