version: "3.9"

services:
  db:
    command:
      - "postgres"
    image: library/postgres:10.12
    environment:
      - POSTGRES_DB=postgres_client_test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "30123:5432"